- initializers/sequelize.js
- package.json
Soon to be deprecated (2.1).
Also remove deprecation messages, which is nice.
> Use sequelize promises instead of events

- README.md
Update association example to a working version.
> update association example to new style intializer.

- initializers/sequelize.js
New PR to separate out fix for automigrate.
> fix automigrate alone.

- initializers/sequelize.js
> align initializer startPriority with actionhero redis initializer

- initializers/sequelize.js
SELECT NOW(); is not a valid query in sqlite. This commit creates a separate functional test query for the dialect :hammer:
> Adds an alternate test method for sqlite

- initializers/sequelize.js
Test function fixed for mssql dialect (no function NOW() on MsSQL server)
> Fix for mssql dialect

- README.md
- config/sequelize.js
- initializers/sequelize.js
- package.json
- scripts/postinstall.js
Also refactored some code. This version warns the user after `npm install` to link the plugin If he's using actionhero 13 or higher.
> Updated the plugin to contain more useful information.

- initializers/sequelize.js
We were running into errors caused by double-quotes being invalid SQL syntax. Removing the quotes fixed the issue.
> fix SQL syntax

- initializers/sequelize.js
- package.json
> Fixed umzug not finding migrations. Added winston logging.

- initializers/sequelize.js
- package.json
Don't show migrations warning If running in test environment, makes sequelize tests easier to read.
> Better support for test environment

- initializers/sequelize.js
> Review business logic behind models import

- README.md
> Review associations best practice

- README.md
- package-lock.json
- package.json
- scripts/postinstall.js
Fixes `postinstall` script to copy config file.
Prevents `postinstall` script from running during development.
Fixes `associations.js` script to properly iterate model object.
Removes all references to `--link` command following install.
Updates `readme` to proper plugin configuration.
> Fixes documentation and install scripts

- classes/sequelize.js
passing config logging to sequelize option.
> fix config.logging

- classes/sequelize.js
- package.json
Default config improves security and removes deprecation warning during startup.
Commit pushes to v1.0.3
>  Adds default for operatorsAliases config

- classes/sequelize.js
- initializers/sequelize.js
> Close sequelize on server stop

- classes/sequelize.js
> Restart server when model changes (only in development mode)

- README.md
- classes/sequelize.js
- config/sequelize.js
- test/config/sequelize.js
Changes example config to use destructuring
Normalizes line endings on config and class files
> Adds note about logging function

- package-lock.json
- package.json
- test/config/sequelize.js
Removes the need for external MySQL server in order to run test.
In memory database is destroyed after each run so no need to drop tables between tests.
> Changes to SQLite for testing

- README.md
Minor corrections to the file paths in the Readme for the new directory structure.
> File Path Corrections

- README.md
One of the devs on my team noticed this in our own local change in my PR. Update to the documentation here too :)
> Fix sequelize-cli documentation, NODE_ENV
